Tighten up the Introduction
Qiskit/openqasm pull request #162
Opened 2021-03-12 16:08 UTC by jwoehr

- Grammar, Syntax, and Usage
- Style (less purple)
- Clarity

2021-03-13 22:04 UTC, taalexander requested changes
Thank you for these changes, I've attached a couple suggestions.

2021-03-13 22:04 UTC, taalexander commented on source/intro.rst
> +different representations of the same program as it is descends from a high-level
```suggestion
different representations of the same program as it is transformed from a high-level
```

2021-03-13 22:04 UTC, taalexander commented on source/intro.rst
> +description to pulse representation.
```suggestion
description to a pulse representation.
```

2021-03-13 22:04 UTC, taalexander commented on source/language/comments.rst
> +permitted, nor may it appear elsewhere than as the first non-comment line.
```suggestion
permitted, nor may it appear elsewhere than the first non-comment line.
```

2021-03-14 03:02 UTC, jwoehr commented
Hmm I've been looking at
- **Aliasing** language/types.html#aliasing
- **Register concatenation and slicing** language/types.html#register-concatenation-and-slicing

and I'm not sure they are consistent with each other.

In a `qubit name[5]` is the whole register `name[0:4]` or `name[0:5]`?

In any case, I will need to correct or enhance my last checking referencing slicing, which, though clearer than other explanation, is probably wrong :)

2021-03-14 03:13 UTC, jwoehr commented
I've corrected what I wrote earlier so it's consistent with the section on slicing, but probably the discussion of slicing should be unified and made a bit clearer.

2021-03-15 01:55 UTC, jwoehr commented
As I read it, the introduction of discussion of register slices in language/types#qubits was superfluous and the description of slicing in language/types#register-concatenation-and-slicing is entirely sufficient, so I have removed the superfluity.

2021-03-15 13:05 UTC, taalexander approved these changes

2021-03-15 13:07 UTC, taalexander commented
Thank you very much for these contributions, it reads much clearer, and several errors we're fixed. We welcome many more 😄 .

2021-03-15 13:07 UTC, merged