Update delays.rst
Qiskit/openqasm pull request #281
Opened 2021-09-23 16:58 UTC by jessica-angel7

### Summary
This is a minor code correction as per the issue #274. For resolving the stretch values uniquely the suggested changes have been done. Kindly review.

### Details and comments

2021-09-23 23:51 UTC, steleman requested changes
The current OpenQASM Spec:

https://qiskit.github.io/openqasm/language/types.html

states the following:

> Declaration and initialization must be done one variable at a time for both quantum and classical types. Comma separated declaration/initialization (int x, y, z) is NOT allowed for any type.

The proposed change seems to directly contradict the current Spec:

```
stretch s, t, u;
```

2021-09-24 06:16 UTC, jessica-angel7 commented
> The current OpenQASM Spec:
> 
> https://qiskit.github.io/openqasm/language/types.html
> 
> states the following:
> 
> > Declaration and initialization must be done one variable at a time for both quantum and classical types. Comma separated declaration/initialization (int x, y, z) is NOT allowed for any type.
> 
> The proposed change seems to directly contradict the current Spec:
> 
> ```
> stretch s, t, u;
> ```

Hi @steleman, I've made the required changes, Please review. :)

2021-09-24 11:10 UTC, steleman reviewed
This looks good.

2021-09-24 11:11 UTC, steleman approved these changes

2021-09-28 11:17 UTC, merged