Added Dynamic Deference & Allocation WG
Qiskit/openqasm pull request #322
Opened 2022-01-29 03:38 UTC by jwoehr

### Summary
Add new Working Group description

### Details and comments
Voted by the TSZC 2022-01-28

2022-01-29 03:43 UTC, jwoehr commented
Voted by TSC 2022-01-28

2022-01-31 15:15 UTC, 1ucian0 commented on WG.md
>  **Questions**:
```suggestion
**Objective**: Define type hierarchy and implicit casting rules.  
**Questions**:
```

2022-01-31 15:16 UTC, 1ucian0 commented on WG.md
>  Members: Colm Ryan, Andrew Cross, Ali Javadi, Blake Johnson, Matthew Amy
These trail spaces create a breakline here. See https://gist.github.com/shaunlebron/746476e6e7a4d698b373

```suggestion
Chair: Niel de Beaudrap  
Members: Colm Ryan, Andrew Cross, Ali Javadi, Blake Johnson, Matthew Amy
```

2022-01-31 15:16 UTC, 1ucian0 commented on WG.md
>  Members: Niel de Beaudrap, Hiroshi Horii, Blake Johnson, Colm Ryan, Luciano Bello, Prasahnt Sivarajah, Yunong Shi, Jake Lishman
```suggestion
Chair: Michael Healy (IBM Quantum)  
Members: Niel de Beaudrap, Hiroshi Horii, Blake Johnson, Colm Ryan, Luciano Bello, Prasahnt Sivarajah, Yunong Shi, Jake Lishman
```

2022-01-31 15:16 UTC, 1ucian0 commented on WG.md
>  **Questions**:
```suggestion
**Objectives**: Define a pragma syntax, standard directives, the standard behavioral expectations for interacting within a toolchain.  
**Questions**:
```

2022-01-31 15:19 UTC, 1ucian0 requested changes
Those extra spaces at the end have a meaning :)

2022-01-31 15:22 UTC, 1ucian0 commented on WG.md
>  Members: Blake Johnson, Colm Ryan, Derek Bolt, Peter Karalekas, Lauren Capelluto, Michael Healy, Prasahnt Sivarajah, Yunong Shi, Steven Heidel
```suggestion
Chair: Thomas Alexander (IBM Quantum)  
Members: Blake Johnson, Colm Ryan, Derek Bolt, Peter Karalekas, Lauren Capelluto, Michael Healy, Prasahnt Sivarajah, Yunong Shi, Steven Heidel
```

2022-01-31 15:23 UTC, jakelishman commented on WG.md
> + * Provide oncrete examples proving this cannot be dealt with in OpenQASM 3 as the spec stands
```suggestion
 * Provide concrete examples proving this cannot be dealt with in OpenQASM 3 as the spec stands
```

2022-01-31 15:52 UTC, 1ucian0 approved these changes

2022-01-31 15:52 UTC, merged